services:
  db:
    image: postgres:16
    container_name: almacen_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: almacen_db
    ports:
      - "5432:5432"
    volumes:
      - almacen_pgdata:/var/lib/postgresql/data

volumes:
  almacen_pgdata:

